name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write   # リリース作成に必須

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build --config Release

    - name: Check build output
      run: ls -R build   # デバッグ用にファイル一覧を表示

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: myapp
        path: build/main*   # ワイルドカードで main or main.exe を拾う

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/main*

